spring:
  application:
    name: user
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
server:
  port: 2010
logging:
  level:
    ROOT: DEBUG
