spring:
  application:
    name: cloudZuul
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
server:
  port: 2000
logging:
  level:
    ROOT: DEBUG
management:
  security:
    enabled: false